fix multi files

diff --git a/.github/workflows/publish-gist.yml b/.github/workflows/publish-gist.yml
--- a/.github/workflows/publish-gist.yml
+++ b/.github/workflows/publish-gist.yml
@@ -10,17 +10,33 @@ on:
       - "mother/src/testFixtures/java/com/github/mehrunessky/demo/blog/mother/PersonMother.java"
       - "mother/build.gradle"
 
+env:
+  GIST_FILES: |
+    mother/src/testFixtures/java/com/github/mehrunessky/demo/blog/mother/PersonMother.java
+    mother/build.gradle
+
 jobs:
   publish:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
 
+      - name: Prepare files for Gist
+        run: |
+          mkdir -p gist
+          while IFS= read -r file; do
+            [ -z "$file" ] && continue
+            if [ ! -f "$file" ]; then
+              echo "❌ File not found: $file"
+              exit 1
+            fi
+            echo "Copy $file"
+            cp "$file" gist/
+          done <<< "$GIST_FILES"
+
       - name: Publish to Gist
         uses: exuanbo/actions-deploy-gist@v1
         with:
           token: ${{ secrets.GIST_TOKEN }}
           gist_id: 7dbb4bb4742a858061b947ba4dc220d1
-          file_path: |
-            mother/src/testFixtures/java/com/github/mehrunessky/demo/blog/mother/PersonMother.java
-            mother/build.gradle
+          file_path: gist
